### ISSUE TITLE
Test run the program to generate an observation script

### ISSUE THREAD

**Issue by wadawson** [paralens/decam-pals#3]

**Comment by wadawson** [comment]
I can run the scripts to create the necessary observing scripts. There are still some issues with creating the figures (#4) but since those are not critical I will consider this closed from my end. I am switching this issue over to @nrgolovich to make sure that he can run the scripts as well.

**Comment by nrgolovich** [comment]
I can generate the scripts as well. Plotting is not working as of yet, but this is now closed on my end too.
