### ISSUE TITLE
Error creating some of the survey plots

### ISSUE THREAD

**Issue by wadawson** [paralens/decam-pals#4]
I was running the commands like: `python bin/plot_csv.py pals_lmc.csv` after installing skymap and I get the following error. I don't know if this means that something hasn't been committed to the decam-pals repo or if I need to be working off the bleeding edge skymap repo. Help is appreciated but this is not critical since it is just creating visualizations.

> Traceback (most recent call last):
  File "bin/plot_csv.py", line 162, in <module>
    plot_fields(outfile,fields)
  File "bin/plot_csv.py", line 133, in plot_fields
    if not args.no_macho: draw_macho(smap,macho)
  File "bin/plot_csv.py", line 87, in draw_macho
    smap.draw_macho(fields['RA'],fields['DEC'],**kwargs)
AttributeError: 'SurveySkymap' object has no attribute 'draw_macho'

**Comment by kadrlica** [comment]
Yeah, you need to checkout the `pals` branch of `skymap`. I think I can also safely merge with master.

**Comment by wadawson** [comment]
That's cool. I can just work off the branch if it is easier for you. Also note that I get the following error when attempting to generate the gifs:

`Exception: $OBZTAK_SURVEY environment variable not set.`

Do I need to run `./bin/prepare_survey` in obztak with some options to create the necessary environment variable?

**Comment by kadrlica** [comment]
No, you need to set it to `export OBZTAK_SURVEY=bliss` in the shell.

**Comment by kadrlica** [comment]
I wasn't planning to fully support the plotting, but happy that you are trying it out (and it'd be great if it actually works).

**Comment by nrgolovich** [comment]
I have the plotting working. There were a host of deprecation warnings, but the code worked for me. 

![pals_lmc](https://user-images.githubusercontent.com/5620288/35936861-5dd5601e-0bf9-11e8-9ec8-244a4a3d48fd.png)

**Comment by kadrlica** [comment]
Are most of the warnings related to `pandas` and `numpy`? (My development environment is ~1 year old, so I'm not especially surprised.)

**Comment by kadrlica** [comment]
@wadawson @nrgolovich Something that you guys can now do is move the fields around. For example, you should be able to change the RA, DEC of one of the fields in the csv file, make the plot, then make the json files.

**Comment by nrgolovich** [comment]
@kadrlica the warnings were from mpl_toolkits/basemap

...envs/skymap/lib/python2.7/site-packages/mpl_toolkits/basemap/__init__.py:1303: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead

**Comment by kadrlica** [comment]
Ok, thanks, I think this is outside of my control. I'm closing this issue.
